---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: {{ K8S_AUTH_NAMESPACE }}
spec:
  ports:
  - name: dex
    port: 5556
    protocol: TCP
    targetPort: 5556
  selector:
    app: dex
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dex-ingress
  namespace: {{ K8S_AUTH_NAMESPACE }}
spec:
  tls:
  - hosts: 
    - {{ OIDC_ISSUER_URL }}
    secretName: {{ OIDC_ISSUER_URL }}.tls
  rules:
  - host: {{ OIDC_ISSUER_URL }}
    http:
      paths:
      - path: /dex
        backend:
          serviceName: dex
          servicePort: 5556