---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: {{ K8S_AUTH_NAMESPACE }}
spec:
  ports:
  - name: dex
    port: 5556
    protocol: TCP
    targetPort: 5556
  selector:
    app: dex
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dex-ingress
  namespace: {{ K8S_AUTH_NAMESPACE }}
  annotations:
    kubernetes.io/tls-acme: 'true'
    ingress.kubernetes.io/force-ssl-redirect: 'true'
spec:
  rules:
    - host: {{ MCMP_UI }}
      http:
        paths:
          - backend:
              serviceName: dex
              servicePort: 5556
            path: /k8stools/dex
  tls:
    - hosts:
        - {{ MCMP_UI }}
      secretName: {{ MCMP_UI }}.tls
