apiVersion: v1
kind: Service
metadata:
  name: keycloak-proxy
  namespace: {{ K8S_AUTH_NAMESPACE }}
spec:
  ports:
  - name: keycloak-proxy
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: keycloak-proxy
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: loginapp-ingress
  namespace: {{ K8S_AUTH_NAMESPACE }}
spec:
  rules:
  - host: {{ LOGIN_APP_URL }}
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak-proxy
          servicePort: 80
