apiVersion: v1
kind: Service
metadata:
  name: keycloak-proxy
  namespace: {{ K8S_AUTH_NAMESPACE }}
spec:
  ports:
  - name: keycloak-proxy
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    name: keycloak-proxy
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: loginapp-ingress
  namespace: {{ K8S_AUTH_NAMESPACE }}
spec:
  tls:
  - hosts: 
    - {{ LOGIN_APP_URL }}
    secretName: {{ LOGIN_APP_URL }}.tls
  rules:
  - host: {{ LOGIN_APP_URL }}
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak-proxy
          servicePort: 443
