apiVersion: v1
kind: Service
metadata:
  name: keycloak-proxy
  namespace: {{ K8S_AUTH_NAMESPACE }}
spec:
  ports:
  - name: keycloak-proxy
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: keycloak-proxy
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: loginapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  namespace: {{ K8S_AUTH_NAMESPACE }}
spec:
  rules:
  - host: {{ MCMP_UI }}
    http:
      paths:
      - path: /tools-login/(.*)
        backend:
          serviceName: keycloak-proxy
          servicePort: 80
  tls:
  - hosts:
      - {{ MCMP_UI }}
    secretName: {{ MCMP_UI }}.tls
