apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak-proxy
  namespace: {{ K8S_AUTH_NAMESPACE }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: keycloak-proxy
      annotations:
        repository: https://github.com/gambol99/keycloak-proxy
    spec:
      containers:
      - name: proxy
        image: {{ K8S_KEYCLOAK_PROXY_IMAGE }}
        imagePullPolicy: Always
        args:
          - --listen=:443
          - --upstream-url=https://kubernetes-dashboard.{{ K8S_DASHBOARD_NAMESPACE }}
          - --discovery-url=https://{{ OIDC_ISSUER_URL }}/dex
          - --client-id=loginapp
          - --skip-upstream-tls-verify
          - --redirection-url=https://{{ LOGIN_APP_URL }}
#          - --secure-cookie=false
          - --client-secret=4TORGiNV9M54BTk1v7dNuFSaI6hUjfjr
          - --scopes=groups 
          - --enable-authorization-header
          - --skip-openid-provider-tls-verify
          - --resources=uri=/*
