apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
#    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
#    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  name: external-auth-oauth2
  namespace: {{ K8S_DASHBOARD_NAMESPACE }}
spec:
  rules:
  - host: {{ MCMP_UI }}
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
        path: /dash
  tls:
  - hosts:
    - {{ MCMP_UI }}
    secretName: {{ MCMP_UI }}.tls
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: {{ K8S_AUTH_NAMESPACE }}
spec:
  rules:
  - host: {{ MCMP_UI }}
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /oauth2
  tls:
  - hosts:
    - {{ MCMP_UI }}
    secretName: {{ MCMP_UI }}.tls