apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: {{ K8S_AUTH_NAMESPACE }}
spec:
  rules:
  - host: {{ LOGINAPP_URL }}
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /oauth2
  tls:
  - hosts:
    - {{ LOGINAPP_URL }}
    secretName: {{ MCMP_UI }}.tls