apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: {{ OIDC_ISSUER_URL }}.tls
  namespace: {{ K8S_AUTH_NAMESPACE }}
type: kubernetes.io/tls
data:
  tls.crt: {{ from_file('ssl/cert.pem') }}
  tls.key: {{ from_file('ssl/key.pem') }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: {{ LOGIN_APP_URL }}.tls
  namespace: {{ K8S_AUTH_NAMESPACE }}
type: kubernetes.io/tls
data:
  tls.crt: {{ from_file('ssl/cert.pem') }}
  tls.key: {{ from_file('ssl/key.pem') }}